language: ruby
rvm:
- 2.2.5

git:
  submodules: false
branches:
  only:
  - master

sudo: false

script: ./scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  bucket: test.shuttleworthfoundation.org
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    branch: master

notifications:
  slack: shuttleworth-gang:sQhUplrgC8R4pHqcMFaXZgtC
