##
# SITE SETTINGS
##
title: The Shuttleworth Foundation
email: jason@shuttleworthfoundation.org
description: "We're the Shuttleworth Foundation. We provide funding for dynamic leaders who are at the forefront of social change."
baseurl: ""
url: "http://shuttleworthfoundation.org"
twitter_username: ShuttleworthFdn
github_username: jasonhudson

intake:
  open: false
  reopen: 1 May 2019
  current: 1 September 2019
  next: September 2019
  close: 1 June 2019
  notify: 1 July 2019

exclude: [Makefile, README.md, vendor, Gemfile]

##
# BUILD SETTINGS
##
markdown: kramdown
permalink: pretty
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

plugins_dir: _plugins
plugins:
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-contentblocks

##
# JEKYLL-ARCHIVES
##

jekyll-archives:
  enabled: ['year', 'tags']
  permalinks:
    year: '/thinking/:year/'
    tag: '/thinking/tag/:name/'
  layouts:
    year: archive/year
    tag: archive/tag

##
# COLLECTIONS
##
collections:
  fellows:
    output: true
  team:
    output: true

